---
title: "*Zosterops* mapping"
format: html
toc: true
toc-title: Document Contents
number-sections: true
embed-resources: true
---

## Import data
```{r}
#load in each library used for mapping
library(vcfR) #v1.14.0
library(ggplot2) #v3.4.1
library(maps) #v3.4.1
library(sf) #v1.0-12
library(RColorBrewer) #v1.1-3

#read in the vcf 
vcfR <- read.vcfR("~/Desktop/cali.zosterops.rad/filtered.snps.vcf.gz")

#read in sample info csv
sample.info<-read.csv("~/Desktop/cali.zosterops.rad/zosterops.trimmed.RAD.sampling.csv")

#prune sampling dataframe so that it matches the files retained in the vcf
samps<-sample.info[sample.info$ID %in% colnames(vcfR@gt)[-1],]
```

```{r}
#split df by species
spec.dfs<-split(samps, samps$Species)

#init sampling.df which will be a df of samples grouped by unique lat/long
sampling.df<-data.frame(NULL)
#use a for loop to split the dataframe by species and summarize the number of individuals sampled at each locality for each species
for (i in names(spec.dfs)){
  samps<-spec.dfs[[i]] %>% dplyr::group_by(lat, long) %>% dplyr::summarize(count=dplyr::n())
  df<-cbind(rep(i, times=nrow(samps)), samps)
  sampling.df<-as.data.frame(rbind(sampling.df, df))
}
#fix colnames
colnames(sampling.df)<-c("species","lat","long","count")

#remove the three wintering erythropleurus samples
sampling.df<-sampling.df[-1,]
  
#make base world map
pac<-map_data("world")

# plot just simplex
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  #crop world map to the coordinates you're interested in
  coord_sf(xlim = c(90, 145), ylim = c(-10, 50)) + 
  #add sampling localities as dots where the species = "simplex"
  geom_point(data = sampling.df[sampling.df$species == "simplex",], aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  #set color
  scale_fill_manual(values=c("#CC6677"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

# plot just palpebrosus
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(90, 145), ylim = c(-10, 50)) + 
  geom_point(data = sampling.df[sampling.df$species == "palpebrosus",], aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#CC6677"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

# plot just nigrorum
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(90, 145), ylim = c(-10, 50)) + 
  geom_point(data = sampling.df[sampling.df$species == "nigrorum",], aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#DDCC77"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

# plot just japonicus
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(90, 145), ylim = c(-10, 50)) + 
  geom_point(data = sampling.df[sampling.df$species == "japonicus",], aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#882255"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

# plot just everetti
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(90, 145), ylim = c(-10, 50)) + 
  geom_point(data = sampling.df[sampling.df$species == "everetti",], aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#117733"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

# plot just erythropleurus
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(90, 145), ylim = c(-10, 50)) + 
  geom_point(data = sampling.df[sampling.df$species == "erythropleurus",], aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#332288"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)


# plot all native samples
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(90, 145), ylim = c(-10, 48)) + 
  geom_point(data = sampling.df, aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#332288","#117733","#CC6677","#DDCC77","#882255","#88CCEE"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 6), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

#save the sampling plot
#ggsave("~/Desktop/cali.zosterops.rad/full.map.pdf", width = 9, height = 6.5, units= "in")
```

```{r}
# plot hawaii samples
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(-161, -153), ylim = c(18, 23)) + 
  geom_point(data = sampling.df, aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=rep("white", times=6))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(nrow = 1, order = 2))+
  theme(legend.position = NULL)
#save
#ggsave("~/Desktop/cali.zosterops.rad/hawaii.map.pdf", width = 5.5, height = 3, units= "in")

#plot LA samples
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(-125, -114), ylim = c(32, 42)) + 
  geom_point(data = sampling.df, aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =1, show.legend=TRUE) +
  borders("state")+
  theme_classic()+
  scale_fill_manual(values=rep("black", times=6))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 4), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(nrow = 1, order = 2))+
  theme(legend.position = NULL)
#save
#ggsave("~/Desktop/cali.zosterops.rad/tall.cali.map.pdf", width = 5.5, height = 8, units= "in")
```

